pins:
  clk_pin: 13
  dt_pin: 5
  sw_pin: 6

volumio:
  host: localhost
  port: 3000
  api_url: "http://localhost:3000/api/v1"
  connection_timeout: 5  # Timeout in seconds for Volumio API connection

display:
  icon_dir: "/home/volumio/Quadify/src/assets/images"
  default_album_art: "/home/volumio/Quadify/src/assets/images/albumart.jpg"
  loading_gif_path: "/home/volumio/Quadify/src/assets/images/Loading.gif"
  screensaver_gif_path: "/home/volumio/Quadify/src/assets/images/geo.gif"  
  logo_path: "/home/volumio/Quadify/src/assets/images/logo.png"

  rotation: 0  # Set rotation if needed (0, 90, 180, 270)


  fonts:
    playback_large:
      path: "/home/volumio/Quadify/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 45
    playback_medium:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 18
    playback_small:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    artist_font:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    song_font:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 14
    data_font:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 10
    menu_font:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    menu_font_bold:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Bold.ttf"
      size: 12
    clock_large:
      path: "/home/volumio/Quadify/src/assets/fonts/DSEG7Classic-LightItalic.ttf"
      size: 35
    sample_rate:
      path: "/home/volumio/Quadify/src/assets/fonts/DSEG7Classic-LightItalic.ttf"
      size: 46
    sample_rate_khz:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    radio_title:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 15
    radio_bitrate:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 12
    volume_small:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 8

      # Minimal fonts
    minimal_volume:
      path: "/home/volumio/Quadify/src/assets/fonts/Montserrat-Bold.ttf"
      size: 15
    minimal_service:
      path: "/home/volumio/Quadify/src/assets/fonts/Montserrat-Regular.ttf"
      size: 27
    minimal_data:
      path: "/home/volumio/Quadify/src/assets/fonts/Montserrat-Regular.ttf"
      size: 10

      # Clock fonts (for hours/minutes)
    clock_sans:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 40
    clock_dots:
      path: "/home/volumio/Quadify/src/assets/fonts/led_counter-7.ttf"
      size: 40
    clock_digital:
      path: "/home/volumio/Quadify/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 30
    clock_bold:
      path: "/home/volumio/Quadify/src/assets/fonts/Montserrat-Bold.ttf"
      size: 42

    # Smaller date fonts (for optional date line)
    clockdate_sans:
      path: "/home/volumio/Quadify/src/assets/fonts/OpenSans-Regular.ttf"
      size: 15
    clockdate_dots:
      path: "/home/volumio/Quadify/src/assets/fonts/led_counter-7.ttf"
      size: 15
    clockdate_digital:
      path: "/home/volumio/Quadify/src/assets/fonts/DSEG7Classic-Light.ttf"
      size: 10
    clockdate_bold:
      path: "/home/volumio/Quadify/src/assets/fonts/Montserrat-Regular.ttf"
      size: 10

  refresh_rate: 60  # Display refresh rate in Hz

  cache_images: true  # Cache frequently used images for faster access
  preload_images:
    - "/home/volumio/Quadify/src/assets/images/webradio.png"
    - "/home/volumio/Quadify/src/assets/images/mpd.png"
    - "/home/volumio/Quadify/src/assets/images/library.png"
    - "/home/volumio/Quadify/src/assets/images/stream.png"
    - "/home/volumio/Quadify/src/assets/images/tidal.png"
    - "/home/volumio/Quadify/src/assets/images/qobuz.png"
    - "/home/volumio/Quadify/src/assets/images/spop.png"      
    - "/home/volumio/Quadify/src/assets/images/playlists.png"
    - "/home/volumio/Quadify/src/assets/images/default.png"
    - "/home/volumio/Quadify/src/assets/images/nas.png"
    - "/home/volumio/Quadify/src/assets/images/usb.png"
    - "/home/volumio/Quadify/src/assets/images/volume.png"
    - "/home/volumio/Quadify/src/assets/images/config.png"

mcp23017_address: 0x27

logging:
  level: "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR
  log_file: "/home/volumio/Quadify/quadifyclean.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


